<?php
$error = \Model\Error::GetError();
if ($error != null) {
?>
    <div class="alert alert-<?php echo $error["Type"]; ?> alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?php echo $error["Content"]; ?>
    </div>
<?php
}
$isCheck = isset($_COOKIE["GhiNhoMatKhau"]) ? "checked" : "";
$taiKhoan = isset($_COOKIE["TaiKhoan"]) ? $_COOKIE["TaiKhoan"] : "";
?>
<div class="login-logo">
    <a href="">Đăng nhập</a>
</div><!-- /.login-logo -->
<form action="" method="post">
    <div class="form-group has-feedback">
        <input type="text" value="<?php echo $taiKhoan; ?>" required="required" name="TaiKhoan" class="form-control" placeholder="Tài Khoản">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
        <input type="password" required="required" name="MatKhau" class="form-control" placeholder="Mật Khẩu">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="checkbox icheck">
                <label>
                    <input <?php echo $isCheck; ?> type="checkbox" name="GhiNhoMatKhau" value="1"> Ghi Nhớ Mật Khẩu
                </label>
            </div>
        </div>
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary btn-block">Đăng Nhập</button>
        </div>
    </div>
</form>
</br>
<div class="clearfix"></div>
<summary class="form-text text-muted text-center ">
    <a href="/index.php?controller=login&action=resetpass">Quên Mật Khẩu</a>
</summary>