<!DOCTYPE html>
<html lang="vi">

<head>
    <title>Login | Share Investment</title>
    <link href="/public/admin_blue/css/application.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="img/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="namdong92@gmail.com">
    <meta charset="utf-8">
</head>

<body class="background-dark">
    <div class="single-widget-container">
        <section class="widget login-widget">
            <?php
            include $_Content;
            ?>
        </section>
    </div> 
    <script src="/public/admin_blue/lib/jquery/dist/jquery.min.js"></script>
    <script src="/public/admin_blue/lib/jquery-pjax/jquery.pjax.js"></script>
    <script src="/public/admin_blue/lib/bootstrap-sass-official/assets/javascripts/bootstrap.js"></script>
    <script src="/public/admin_blue/lib/widgster/widgster.js"></script>
    <script src="/public/admin_blue/lib/underscore/underscore.js"></script>

    <script src="/public/admin_blue/js/app.js"></script>
    <script src="/public/admin_blue/js/settings.js"></script>
</body>

</html>