<ol class="breadcrumb" >
    <li><a href="/backend" >Home</a></li>
    <li> Cơ Cấu Tổ Chức </li>
</ol>

<div class="container-fluid"  ng-controller="searchCtrl" >
    <form method="get" action="/nhanvien/index/index/">
        <div class="form-group d-flex" >
            <label class="btn btn-default" ><input ng-change="isShowMore(showMore);" ng-model="showMore" style="display: none" type="checkbox" ><i class="fa fa-filter" ></i></label>
            <input id="keyword" class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type=""  >
            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit"  >
                <i class="fa fa-search"  ></i>
            </button>
        </div>
        <div class="row " ng-show="showMore" >
            <div class="col-md-3"  >
                <?php
                $options = \Model\OptionsService::GetGroupsToSelect("congty");
                $options = ["" => "Chọn Công Ty"] + $options;
                $congty = isset($_GET[Model\Users\UserInfor::CongTy]) ? $_GET[Model\Users\UserInfor::CongTy] : "";
                Model\FormCommon::Select("Công Ty", Model\Users\UserInfor::CongTy, $options, ["value" => $congty, "class" => "form-control"])->renderHTML();
                ?>
            </div>
        </div>
    </form>
    <div class="clearfix">

    </div>
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh Sách Nhân Viên</h3>
            <div class="box-tools" >
                <?php
                echo Model\User::btnThem();
                ?>

            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th style="width: 100px" class="hidden-xs" >
                            <label>
                                Hình ảnh
                                <input  type="checkbox" ng-model="showImg" >
                            </label>
                        </th>
                        <th>Nhân Viên</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($Items as $index => $user) {
                        $_user = new \Module\nhanvien\Model\NhanVien($user);
                        ?>
                        <tr>
                            <th class="text-center hidden-xs" >
                                <div ng-show="showImg" >
                                    <img style="margin: auto;height: 60px;" onerror="this.src='/public/no-user.jpg'" src="<?php echo $_user->UserInfor(\Model\Users\UserInfor::HinhNhanVien)->Val; ?>" class="img img-responsive" alt="alt" title="alt" >
                                </div>
                            </th>
                            <th  >
                                <div class="d-flex"  >
                                    <div class=""  style="min-width: 220px">
                                        <p><?php echo $_user->Name; ?></p>
                                        <p><i class="fa fa-phone" ></i> <?php echo $_user->UserInfor("Phone")->Val; ?></p>
                                        <p><i class="fa fa-envelope" ></i> <?php echo $_user->Email; ?></p>

                                    </div>
                                    <div class="text-right">
                                        <?php
                                        echo $_user->btnSua();
                                        ?>
                                    </div>
                                </div>
                            </th>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>

        </div>
        <div class="box-footer" >
            <div  class="d-flex">
                <?php
                \Model\FormCommon::Select("", "", [10, 20, 50, 100], [
                    "style" => "max-width:70px;",
                    "class" => "form-control",
                    "value" => $pageNumber,
                    "onchange" => "SoDongHienThi(this.value)",
                        ]
                )->render();
                ?>
                <?php
                $linkPhanTrang = "/nhanvien/index/index/?indexPage=[i]&pageNumber={$pageNumber}";
                echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" >
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/nhanvien/index/index/?indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>
