<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li> Quản Lý Tài Khoản </li>
</ol>

<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <form method="get" action="">
                <div class="form-group d-flex">
                    <input class="form-control" name="controller" value="quanlyusers" type="hidden">
                    <input class="form-control" name="action" value="index" type="hidden">
                    <input class="form-control" name="indexPage" value="<?php echo $indexPage ?>" type="hidden">
                    <input class="form-control" name="pageNumber" value="<?php echo $pageNumber ?>" type="hidden">
                    <input class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type="" placeholder="Tìm kiếm theo tên tài khoản, họ và tên hoặc Email ...">
                    <button class="btn btn-primary" name="btnTim" type="submit">Tìm Kiếm</button>
                </div>
            </form>
        </div>
        <div class="box-header">
            <h3 class="box-title">Danh Sách Tài Khoản</h3>
            <div class="box-tools">
                <?php
                \Model\FormRender::HuongDan("danhsachuser", "Hướng dẫn quản lý tài khoản");
                echo Model\User::btnThem();
                ?>

            </div>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Tài Khoản</th>
                        <th>Họ & Tên</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($DanhSachTaiKhoan as $index => $user) {
                        $_user = new Model\User($user);
                    ?>
                        <tr>
                            <th>

                                <?php
                                echo $_user->btnSua();
                                echo $_user->btnXoa();
                                ?>
                            </th>
                            <th><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></th>
                            <th><?php echo $_user->Username; ?></th>
                            <th><?php echo $_user->Name; ?></th>
                            <th><?php echo $_user->Email; ?></th>
                        </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>

        </div>
        <div class="box-footer">
            <div class="d-flex">
                <?php
                \Model\FormCommon::Select(
                    "",
                    "",
                    [10, 20, 50, 100],
                    [
                        "style" => "max-width:150px;",
                        "class" => "form-control",
                        "value" => $pageNumber,
                        "onchange" => "SoDongHienThi(this.value)",
                    ]
                )->render();
                ?>
                <?php
                $linkPhanTrang = "/index.php?controller=quanlyusers&action=index&indexPage=[i]&pageNumber={$pageNumber}";
                echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?controller=quanlyusers&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>