<ol class="breadcrumb">
    <li><a href="/backend/"><i class="fa fa-dashboard"></i>&nbsp; Dashboard</a></li>
    <li class="active text-capitalize">Danh sách phiếu nhập kho</li>
</ol>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header">
                    <form method="get" action="/backend/nhapkho/">
                        <div class="form-group d-flex" style="margin-bottom: 0px;">
                            <div class="col-sm-12 form-group" style="margin-bottom: 0px;">
                                <?php
                                \Model\FormSearch::KeyWordDashboard("Mã phiếu hoặc nội dung phiếu", $_REQUEST['keyword'] ?? null, "Nhập vào mã phiếu hoặc nội dung phiếu để tìm kiếm")->renderHtml2(null, null, 'glyphicon glyphicon-barcode form-control-feedback');
                                ?>
                            </div>
                            <div class="col-sm-2 form-group" style="margin-bottom: 0px;">
                                <div class="form-group has-success has-feedback">
                                    <label for="inputSuccess2" class="text-capitalize"><em>Nhấn vào đây&nbsp; </em><i class="fa fa-check"></i></label>
                                    <button type="submit" style="border-radius: 5px;" class="form-control btn btn-success" name="btnTim">
                                        <i class="fa fa-search-plus"></i>&nbsp;&nbsp; Tìm kiếm
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="box-header">
                    <div class="box-tools">
                        <div class="box-tools ">
                            <?php
                            if (\Model\Permission::CheckPremision([
                                \Model\User::QuanLy, \Model\User::Admin
                            ], []) == true) {
                            ?>
                                <a class="btn btn-warning" <?php echo \Model\FormRender::ToolTip("Xuất Excel danh sách phiếu nhập"); ?> href="/thongke/ExportDSPhieuNhap">
                                    <i class="fa fa-filter"></i> Export danh sách</a>
                            <?php
                            }
                            ?>
                            <a class="btn btn-primary" <?php echo \Model\FormRender::ToolTip("Xem danh sách chi tiết tất cả phiếu nhập"); ?> href="/backend/dsnhapchitiet">
                                <i class="fa fa-history"></i> Lịch sử nhập chi tiết</a>
                        </div>
                    </div>
                    <h3 style="text-align: center;" class="text-uppercase">Danh sách phiếu nhập kho</h3>
                </div>
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6"></div>
                            <div class="col-sm-6"></div>
                        </div>
                        <fieldset>
                            <legend>Danh sách phiếu nhập</legend>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">STT</th>
                                                <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" >Mã phiếu</th>
                                                <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Nội dung phiếu</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Ngày nhập</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Tổng tiền</th>
                                                <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Ghi chú</th>
                                                <!-- <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Tổng tiền</th> -->
                                                <!-- <th></th> -->
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php

                                            use Model\Common;
                                            use Model\Notions;
                                            use Model\ThongKe;
                                            use Module\quanlythuoc\Model\SanPham;

                                            $index = 0;
                                            $danhsach = $data['items'];
                                            foreach ($danhsach as $value) { ?>
                                                <?php
                                                ?>
                                                <tr role="row" class="even">
                                                    <td class="sorting_1 text-center"><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></td>
                                                    <td><?php echo $value['IdPhieu']; ?></td>
                                                    <td><?php echo $value["NoiDungPhieu"]; ?></td>
                                                    <td><?php echo Common::ForMatDMY($value["NgayNhap"]); ?></td>
                                                    <td><?php echo Common::ViewPrice($value["TongTien"]); ?></td>
                                                    <!-- <td><?php echo Common::ViewNumber($value['TongSoLuong']); ?></td> -->
                                                    <td><?php echo $value['GhiChu']; ?></td>
                                                    <td>
                                                        <a href="/backend/lichsunhap/?id=<?php echo $value['IdPhieu']; ?>" <?php echo \Model\FormRender::ToolTip("Thông tin chi tiết phiếu"); ?> type="button" class="btn btn-default"><i class="fa fa-eye"></i>&nbsp;Chi tiết</a>
                                                    </td>
                                                </tr>
                                            <?php
                                                $index++;
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                    <div class="box-footer">
                                        <div class="d-flex">
                                            <?php
                                            \Model\FormCommon::Select(
                                                "",
                                                "",
                                                [10, 20, 50, 100],
                                                [
                                                    "style" => "max-width:150px;",
                                                    "class" => "form-control",
                                                    "value" => $pageNumber,
                                                    "onchange" => "SoDongHienThi(this.value)",
                                                ]
                                            )->render();
                                            ?>
                                            <?php
                                            $linkPhanTrang = "/index.php?controller=backend&action=nhapkho&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                                            echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?controller=backend&action=nhapkho&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>