<?php
$error = \Model\Error::GetError();
if ($error != null) {
?>
    <div class="alert alert-<?php echo $error["Type"]; ?> alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?php echo $error["Content"]; ?>
    </div>
<?php
}
$isCheck = isset($_COOKIE["GhiNhoMatKhau"]) ? "checked" : "";
$taiKhoan = isset($_COOKIE["TaiKhoan"]) ? $_COOKIE["TaiKhoan"] : "";
?>
<!-- <div class="login-logo">
    <a href="">Đăng nhập</a>
</div>
<form action="" method="post">
    <div class="form-group has-feedback">
        <input type="text" value="<?php echo $taiKhoan; ?>" required="required" name="TaiKhoan" class="form-control" placeholder="Tài Khoản">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
        <input type="password" required="required" name="MatKhau" class="form-control" placeholder="Mật Khẩu">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="checkbox icheck">
                <label>
                    <input <?php echo $isCheck; ?> type="checkbox" name="GhiNhoMatKhau" value="1"> Ghi Nhớ Mật Khẩu
                </label>
            </div>
        </div>
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary btn-block">Đăng Nhập</button>
        </div>
    </div>
</form>
</br>
<div class="clearfix"></div>
<summary class="form-text text-muted  ">
    <a href="/index.php?controller=login&action=resetpass">Quên Mật Khẩu</a>
</summary> -->
<header class="text-align-center">
    <h4>Đăng nhập</h4>
</header>
<div class="body">
    <form class="no-margin" action="" method="post">
        <fieldset>
            <div class="form-group">
                <label for="email">Tài khoản</label>
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="fa fa-user"></i>
                    </span>
                    <input type="text" value="<?php echo $taiKhoan; ?>" required="required" name="TaiKhoan" class="form-control input-lg input-transparent" placeholder="Tài Khoản">
                    <!-- <input id="email" type="email" class="form-control input-lg input-transparent" placeholder="Your Email"> -->
                </div>
            </div>
            <div class="form-group">
                <label for="password">Mật khẩu</label>
                <div class="input-group input-group-lg">
                    <span class="input-group-addon">
                        <i class="fa fa-lock"></i>
                    </span>
                    <input type="password" required="required" name="MatKhau" class="form-control input-lg input-transparent" placeholder="Mật Khẩu">
                </div>
            </div>
        </fieldset>
        <div class="form-actions">
            <button type="submit" class="btn btn-block btn-lg btn-danger">
                <small>Đăng nhập</small>
                <span class="small-circle"><i class="fa fa-caret-right"></i></span>
            </button>
            <a class="forgot" href="/index.php?controller=login&action=resetpass">Quên Mật Khẩu</a>
        </div>
    </form>
</div>
<!-- <footer>
    <div class="facebook-login">
        <a href="">
            <span><i class="fa fa-facebook-square fa-lg"></i> LogIn with Facebook</span>
        </a>
    </div>
</footer> -->