<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=danhmuc&action=index"> Danh Mục Thuốc</a></li>
    <li> Thêm Danh Mục </li>
</ol>
<?php

use Module\quanlythuoc\Model\DanhMuc;
use Module\quanlythuoc\Model\DanhMuc\FormDanhMuc;


$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Danh Mục</h3>
            <div class="box-tools">
                <?php
                // Module\quanlythuoc\Model\btnHtml::btnViewDanhMuc();
                \Model\FormRender::HuongDan("themdanhmuc","Hướng dẫn thêm danh mục")
                ?>

            </div>
        </div>
        <!-- <div class="box-body"> -->
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $dm = new FormDanhMuc();
                ?>
                <div class="">
                    <div class="col-md-6">
                        <?php $dm->Id(DanhMuc::CreatId())->renderHtml(); ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Name()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Link()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->GhiChu()->renderHtml();  ?>
                    </div>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                    </div>
                </div>
        </form>
    </div>
</div>
</div>