<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=danhmuc&action=index"> Danh Mục Thuốc</a></li>
    <li> Sửa Danh Mục </li>
</ol>
<?php

use Module\quanlythuoc\Model\DanhMuc;
use Module\quanlythuoc\Model\DanhMuc\FormDanhMuc;


$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Sửa Danh Mục</h3>
            <div class="box-tools">
                <div class="box-tools">
                    <?php
                    // Module\quanlythuoc\Model\btnHtml::btnViewDanhMuc();
                    \Model\FormRender::HuongDan("suadanhmuc","Hướng dẫn sửa danh mục")
                    ?>
                    
                </div>
            </div>
        </div>
        <!-- <div class="box-body"> -->
        <div class="box-body">
            <form action="" method="post" enctype="multipart/form-data">
                <?php
                $dm = new FormDanhMuc();

                $_item = new DanhMuc($data);
                // var_dump($_item);

                ?>
                <div class="">
                    <div class="col-md-6">
                        <?php $dm->Id($_item->Id)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Name($_item->Name)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Link($_item->Link)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->GhiChu($_item->GhiChu)->renderHtml();  ?>
                    </div>
                    <div class="form-group col-md-12">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Sửa Danh Mục</button>
                    </div>
            </form>
        </div>
    </div>
</div>
</form>
</div>
</div>
</div>