<?php

use Module\dautuchung\Model\DuAnForm;

$duan = json_decode(file_get_contents("data/duan.json"));

?>
<section class="content">
    <form method="POST" action="" id="validation-form">
        <div class="container ">
            <div class="header">
                <h3>Tạo dự án</h3>
            </div>
            <div class=" ">
                <div class=" ">
                    <fieldset>
                        <legend>Thông tin chung</legend>
                        <div class=" ">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php
                                    DuAnForm::Name()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    DuAnForm::GiaTriDuAn()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    DuAnForm::XuatThamGia()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::ThoiGianBatDau()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::ThoiGianDauTu()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::LaiXuatCoBan()->renderHTML();
                                    ?>
                                </div>

                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>Quy mô dự án</legend>
                        <div class=" ">
                            <div class="row">
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::DienTich()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::ChieuNgang()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::ChieuDoc()->renderHTML();
                                    ?>
                                </div>
                            </div>

                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>Địa chỉ</legend>
                        <div class=" ">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php
                                    DuAnForm::DiaChi()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::TinhThanh()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::QuanHuyen()->renderHTML();
                                    ?>
                                </div>
                                <div class="col-md-4">
                                    <?php
                                    DuAnForm::PhuongXa()->renderHTML();
                                    ?>
                                </div>
                            </div>

                        </div>
                    </fieldset>
                    <?php
                    DuAnForm::MoTa()->renderHTML();
                    ?>
                </div>
            </div>
            <div class="box-footer">
                <button class="btn pull-right btn-success">Tạo Dự Án</button>
            </div>
        </div>
    </form>
</section>
<script src="/public/TinhThanh/tinhthanh.js"></script>