<?php

use Views\theme\backend\Functions;
?>
<!DOCTYPE html>
<html>

<head>
    <?php
    Functions::head();
    ?>
</head>

<body ng-app="angApp" class=" <?php echo $_COOKIE["sidebar-toggle"] ?? "" ?> hold-transition skin-blue layout-top-nav ">
    <div class="wrapper">
        <?php
        Functions::header();
        // Functions::leftaside();
        ?>
        <div class="content-wrapper">
            <?php
            $error = \Model\Error::GetError();
            if ($error != null) {
            ?>
                <div class="system-alert alert alert-<?php echo $error["Type"]; ?> alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <?php echo $error["Content"]; ?>
                </div>
            <?php
            }
            ?>
            <?php
            include $_Content;
            ?>
        </div>
        <?php
        Functions::footer();
        ?>
    </div>
    <?php
    Functions::js();
    ?>
</body>

</html>