<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=sanpham&action=index"> Danh Sách Thuốc</a></li>
    <li> Sửa thuốc </li>
</ol>
<?php

use Model\Common;
use Module\quanlythuoc\Model\SanPham;
use Module\quanlythuoc\Model\SanPham\FormSanPham;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Sửa Thuốc</h3>
            <div class="box-tools">
                <?php 
                    \Model\FormRender::HuongDan("suathuoc", "Hướng dẫn sửa thuốc")
                ?>
            </div>
        </div>
        <!-- <div class="box-body"> -->
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $sp = new FormSanPham();

                // var_dump($data);
                $item = new SanPham($items);
                // var_dump($item);
                ?>
                <div class="">
                    <div class="col-md-4">
                        <?php $sp->Id($item->Id)->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Idloaithuoc($item->Idloaithuoc)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Name($item->Name)->renderHtml();  ?>
                    </div>
                    <!-- <div class="col-md-4">
                        <?php $sp->Namebietduoc($item->Namebietduoc)->renderHtml();  ?>
                    </div> -->
                    <div class="col-md-4">
                        <?php $sp->CachDung($item->CachDung)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Soluong($item->Soluong)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->NhaSX($item->NhaSX)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->NuocSX($item->NuocSX)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Solo($item->Solo)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Gianhap($item->Gianhap)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Giaban($item->Giaban)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->DVQuyDoi($item->DVQuyDoi)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->DVT($item->DVT)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Canhbao($item->Canhbao)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php 
                        $sp->Ngaysx($item->Ngaysx)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php 
                        $sp->HSD($item->HSD)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Tacdung($item->Tacdung)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Cochetacdung($item->Cochetacdung)->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Ghichu($item->Ghichu)->renderHtml();  ?>
                    </div>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Lưu Lại</button>
                    </div>
                </div>
        </form>
    </div>
</div>
</form>
</div>
</div>
</div>