<div class="container-fluid" style="" >
    <form action="" enctype="multipart/form-data" method="POST" >
        <div class="panel panel-primary  no-border-radius">
            <div class="panel-heading no-border-radius">
                <h3 class="panel-title">Báo Năng Xuất Ngày</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="">Ngày:</label>
                    <input class="form-control" required="" value="" type="date" name="baonangxuat[Ngay]" >
                </div>
                <div class="form-group">
                    <label for="">Khách Hàng:</label>
                    <select type="text" class="form-control" name="baonangxuat[KhachHang]"  >
                        <option>EU</option>
                        <option>JAPAN</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Mã Hàng:</label>
                    <select type="text" class="form-control" name="baonangxuat[MaHang]"  >
                        <option>#ABC</option>
                        <option>#ABCD</option>
                    </select>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="">PO:</label>
                            <input required="" type="number" class="form-control" name="baonangxuat[PO]" >
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="">Định Mức Ngày:</label>
                            <input required="" type="number" class="form-control" name="baonangxuat[DinhMuc]" >
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="">Sáng:</label>
                            <input required="" type="number" class="form-control"  name="baonangxuat[Sang]" >
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label for="">Chiều:</label>
                            <input required="" type="number" class="form-control" name="baonangxuat[Chieu]" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer text-right">
                <button class=" btn btn-success" >Xác Nhận</button>
            </div>
        </div>
    </form>

</div>
