<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Dashboard</a></li>
    <!-- <li><a href="/index.php?controller=thongke">Thống kê</a></li> -->
    <li class="text-capitalize"> Danh sách đơn thuốc trong ngày </li>
</ol>
<?php

use Model\Common;
use Model\FormSearch;
use Module\donthuoc\Model\DonThuoc;

?>
<div class="container-fluid">
    <div class="clearfix">
        <div class="box box-success">
            <div class="box-header">
                <form method="get" action="/donthuoc/index/donthuoctrongngay/">
                    <div class="row">
                        <input name="indate" value="<?php echo date("Y-m-d", time()); ?>" type="hidden">
                        <div class="col-sm-3 form-group">
                            <?php
                            FormSearch::MaDonThuoc($_GET['id'] ?? null)->renderHtml2(null, null, 'glyphicon glyphicon-qrcode form-control-feedback');
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <?php
                            FormSearch::SelectStatus($_GET['status'] ?? null)->renderHtml2(null, null, '');
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <?php
                            FormSearch::NameBenhNhan($_REQUEST['nameBN'] ?? null)->renderHtml2(null, null, 'glyphicon glyphicon-user form-control-feedback');
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <div class="form-group has-success has-feedback">
                                <label for="inputSuccess2" class="text-capitalize"><em>Nhấn vào đây&nbsp; </em><i class="fa fa-check"></i></label>
                                <button type="submit" style="border-radius: 5px;" class="form-control btn btn-success" name="btnTim" id="keyword">
                                    <i class="fa fa-filter"></i>&nbsp; Tìm kiếm theo bộ lọc
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <hr style="border-top: 2px solid #00a65a; margin:0px auto" width="90%" noshade="noshade">
            <h3 class="text-center text-uppercase">Danh sách đơn thuốc trong ngày</h3>
            <div class="box-header" style="padding: 0px 10px;">
                <div class="pull-right">
                    <?php
                    if (\Model\Permission::CheckPremision([
                        \Model\User::QuanLy, \Model\User::Admin
                    ], []) == true) {
                    ?>
                        <a class="btn btn-warning" <?php echo \Model\FormRender::ToolTip("Xuất Excel danh sách những đơn thuốc trong ngày"); ?> href="/thongke/exportdonthuoctrongngay/">
                            <i class="fa fa-filter"></i>&nbsp;Export danh sách</a>
                    <?php
                    }
                    ?>
                </div>
            </div>

            <div class="box-body">
                <fieldset>
                    <legend>Danh sách đơn thuốc trong ngày</legend>
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>STT</th>
                                        <th>Mã đơn thuốc</th>
                                        <th>Thuộc loại đơn</th>
                                        <th>Tên bệnh nhân</th>
                                        <th>Giới Tính</th>
                                        <th>Ngày Sinh</th>
                                        <th>Thời gian khám bệnh</th>
                                        <th>Chẩn đoán</th>
                                        <th>Tình trạng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $danhsach = $data['items'];
                                    foreach ($danhsach as $index => $item) {
                                        $_item = new DonThuoc($item);
                                        // var_dump($_item);
                                    ?>
                                        <tr>
                                            <td class="text-center">
                                                <?php
                                                echo \Module\donthuoc\Model\btnHtml::btnCopyDonThuoc($_item->Id);
                                                echo \Module\donthuoc\Model\btnHtml::btnSuaDonThuoc($_item->Id);
                                                echo \Module\donthuoc\Model\btnHtml::btnchitiet($_item->Id);
                                                ?>
                                            </td>
                                            <td><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></td>
                                            <td><?php echo $_item->Id; ?></td>
                                            <td><?php echo $_item->ThuocLoaiDon(); ?></td>
                                            <td><?php echo $_item->NameBN; ?></td>
                                            <td><?php echo $_item->Gioitinh(); ?></td>
                                            <td><?php echo Common::ForMatDMY($_item->NgaySinh); ?></td>
                                            <td><?php echo $_item->ThoiGianKham; ?></td>
                                            <td><?php echo $_item->ChanDoanBenh; ?></td>
                                            <!-- <td><?php echo $_item->TongNgayDung . " " . "Ngày"; ?></td> -->
                                            <td><?php echo $_item->Status(); ?></td>
                                        </tr>
                                    <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </fieldset>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?module=donthuoc&controller=index&action=donthuoctrongngay&id={$params["id"]}&status={$params["status"]}&nameBN={$params["nameBN"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?module=donthuoc&controller=index&action=donthuoctrongngay&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>