<ol class="breadcrumb">
    <li><a href="/backend/"><i class="fa fa-dashboard"></i>&nbsp; Dashboard</a></li>
    <li><a href="/backend/nhapkho/" class="text-capitalize">Danh sách phiếu nhập</a></li>
    <li class="active text-capitalize">Danh sách nhập chi tiết</li>
</ol>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header">
                    <form method="get" action="/backend/dsnhapchitiet/">
                        <div class="form-group d-flex" style="margin-bottom: 0px;">
                            <div class="col-sm-10 form-group" style="margin-bottom: 0px;">
                                <?php
                                \Model\FormSearch::KeyWordDashboard("Mã phiếu hoặc mã thuốc", $_REQUEST['keyword'] ?? null, "Nhập vào mã phiếu hoặc mã thuốc để tìm kiếm")->renderHtml2(null, null, 'glyphicon glyphicon-barcode form-control-feedback');
                                ?>
                            </div>
                            <div class="col-sm-2 form-group" style="margin-bottom: 0px;">
                                <div class="form-group has-success has-feedback">
                                    <label for="inputSuccess2" class="text-capitalize"><em>Nhấn vào đây&nbsp; </em><i class="fa fa-check"></i></label>
                                    <button type="submit" style="border-radius: 5px;" class="form-control btn btn-success" name="btnTim">
                                        <i class="fa fa-search-plus"></i>&nbsp;&nbsp; Tìm kiếm
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="box-header">
                    <h3 class="text-center text-uppercase" style="margin: 0px;">Danh sách nhập chi tiết</h3>
                    <div class="box-title">
                        <?php
                        if (\Model\Permission::CheckPremision([
                            \Model\User::QuanLy, \Model\User::Admin
                        ], []) == true) {
                        ?>
                            <div class="box-tools float-left">
                                <a class="btn btn-warning" <?php echo \Model\FormRender::ToolTip("Xuất Excel danh sách chi tiết tất cả phiếu nhập"); ?> href="/backend/exportdsnhapchitiet">
                                    <i class="fa fa-filter"></i>&nbsp;Export danh sách</a>
                            </div>
                        <?php
                        }
                        ?>
                    </div>
                </div>
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6"></div>
                            <div class="col-sm-6"></div>
                        </div>
                        <fieldset>
                            <legend>Danh sách nhập chi tiết</legend>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">STT</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Mã phiếu</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Ngày nhập</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Mã thuốc</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Số lô</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nhà sản xuất</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Số lượng</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nước sản xuất</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Giá nhập</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Tổng giá nhập</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php

                                            use Model\Common;
                                            use Model\Notions;
                                            use Model\ThongKe;
                                            use Module\quanlythuoc\Model\SanPham;

                                            $index = 0;
                                            $danhsach = $data['items'];
                                            // var_dump($danhsach);
                                            foreach ($danhsach as $value) { ?>
                                                <?php
                                                $phieu = new \Module\quanlythuoc\Model\PhieuXuatNhap($value["IdPhieu"]);
                                                ?>
                                                <tr role="row" class="even">
                                                    <td class="sorting_1 text-center"><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></td>
                                                    <td><?php echo $value["IdPhieu"]; ?></td>
                                                    <td><?php echo Common::ForMatDMYHIS($phieu->NgayNhap); ?></td>
                                                    <td><?php echo SanPham::GetNameById($value["IdThuoc"]) . " " . "(" . $value["IdThuoc"] . ")"; ?></td>
                                                    <td><?php echo $value["SoLo"]; ?></td>
                                                    <td><?php echo $value['NhaSanXuat']; ?></td>
                                                    <td><?php echo Common::ViewNumber($value['SoLuong']); ?></td>
                                                    <td><?php echo $value['NuocSanXuat']; ?></td>
                                                    <td><?php echo Common::ViewPrice($value['Price']); ?></td>
                                                    <td><?php echo Common::ViewPrice($value['SoLuong'] * $value['Price']); ?></td>
                                                </tr>
                                            <?php
                                                $index++;
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                    <div class="box-footer">
                                        <div class="d-flex">
                                            <?php
                                            \Model\FormCommon::Select(
                                                "",
                                                "",
                                                [10, 20, 50, 100],
                                                [
                                                    "style" => "max-width:150px;",
                                                    "class" => "form-control",
                                                    "value" => $pageNumber,
                                                    "onchange" => "SoDongHienThi(this.value)",
                                                ]
                                            )->render();
                                            ?>
                                            <?php
                                            $linkPhanTrang = "/index.php?controller=backend&action=dsnhapchitiet&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                                            echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?controller=backend&action=dsnhapchitiet&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>