<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=benhnhan&controller=index&action=index"> Danh Sách Khách Hàng</a></li>
    <li> Thêm Khách Hàng </li>
</ol>
<?php

use Module\benhnhan\Model\BenhNhan;
use Module\benhnhan\Model\BenhNhan\FormBenhNhan;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Khách Hàng</h3>
            <div class="box-tools">
                <?php
                // Module\benhnhan\Model\btnHtml::btnViewKhachHang();
                \Model\FormRender::HuongDan("thembenhnhan", "Hướng dẫn thêm bệnh nhân")
                ?>
            </div>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $bn = new FormBenhNhan();
                $benhnhan = new BenhNhan();
                ?>
                <div class="">
                    <div class="col-md-4">
                        <?php $bn->Id($benhnhan->CreatId())->renderHTML(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Name()->renderHTML();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Gioitinh()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Ngaysinh()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->CMND()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Phone()->renderHtml();  ?>
                    </div>
                    <div class="col-md-12">
                        <?php $bn->Address()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4 form-group">
                        <label for="">Tỉnh</label>
                        <select id="tinhThanh" name="BenhNhan[TinhThanh]" class="form-control"></select>
                    </div>
                    <div class="col-md-4 form-group">
                        <label for="">Huyện</label>
                        <select id="quanHuyen" name="BenhNhan[QuanHuyen]" class="form-control"> </select>

                    </div>
                    <div class="col-md-4 form-group">
                        <label for="">Xã</label>
                        <select id="phuongXa" name="BenhNhan[PhuongXa]" class="form-control"> </select>
                    </div>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="/public/TinhThanh/tinhthanh.js"></script>