<?php

use Module\dautuchung\Model\DuAnForm;

$duan = json_decode(file_get_contents("data/duan.json"));

?>

<section class="content-header">
    <h1>
        Dự án
        <small>Tạo dự án</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="/"><i class="fa fa-list"></i> Tạo dự án</a></li>
    </ol>
</section>
<section class="content">
    <form method="POST" action="">
        <div class="container ">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Dự án đất nền</h3>
                </div>
                <div class="box-body">
                    <!-- Color Picker -->
                    <div class="col-md-12">

                        <fieldset>
                            <legend>Thong tin chung</legend>
                            <div class=" ">
                                <div class="row">
                                    <div class="col-md-12">
                                        <?php
                                        DuAnForm::Name()->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        DuAnForm::GiaTriDuAn()->renderHTML();
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend>Quy mô dự án</legend>
                            <div class=" ">
                                <div class="row">
                                    <div class="col-md-4">
                                        <?php
                                        DuAnForm::DienTich()->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        DuAnForm::ChieuNgang()->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        DuAnForm::ChieuDoc()->renderHTML();
                                        ?>
                                    </div>
                                </div>

                            </div>
                        </fieldset>

                    </div>

                    <div class="col-md-12">
                        <fieldset>
                            <legend>Địa chỉ</legend>
                            <div class=" ">
                                <div class="row">
                                    <div class="col-md-12">
                                        <?php
                                        DuAnForm::DiaChi()->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        DuAnForm::TinhThanh()->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        DuAnForm::QuanHuyen()->renderHTML();
                                        ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?php
                                        DuAnForm::PhuongXa()->renderHTML();
                                        ?>
                                    </div>
                                </div>

                            </div>
                        </fieldset>
                    </div>

                    <div class="col-md-12">

                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <?php
                                DuAnForm::ThoiGianBatDau()->renderHTML();
                                ?>
                            </div>
                            <div class="col-md-6">
                                <?php
                                DuAnForm::ThoiGianDauTu()->renderHTML();
                                ?>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <?php
                        DuAnForm::LaiXuatCoBan()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-12">
                        <?php
                        DuAnForm::XuatThamGia()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-12">
                        <?php
                        DuAnForm::MoTa()->renderHTML();
                        ?>
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <button class="btn btn-success">Tạo Mới Dự Án</button>
                </div>
            </div>
        </div>

    </form>
</section>
<script src="/public/TinhThanh/tinhthanh.js"></script>