<?php
$itemGroups = new \Model\OptionsService();
$item = $itemGroups->GetByKeyValue($_Params[0], "NameFunction");
$item = new \Model\OptionsService($item);
?>
<div class="widget">
    <div class="container-fluid">
        <div class="header">
            <div class="box-tools pull-right">
                <a href="/options/post/<?php echo $_Params[0]; ?>/" class="btn btn-primary"><i class="fa fa-plus"></i></a>
            </div>
            <h3>Cài Đặt</h3>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT </th>
                        <th>Mã</th>
                        <th>Tên</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($Items) {
                        foreach ($Items as $k => $item) {
                            $_item = new Model\OptionsService($item);
                    ?>
                            <tr>
                                <th>
                                    <a href="/options/put/<?php echo $_item->Id ?>/">Sửa</a>
                                </th>
                                <th><?php echo $k + 1 ?></th>
                                <th><?php echo $_item->Val ?></th>
                                <th><?php echo $_item->Name ?></th>
                            </tr>
                    <?php
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
        <div>
            <div class="row">
                <div class="col-md-2">
                    <?php
                    \Model\FormCommon::Select(
                        "",
                        "",
                        [10, 20, 50, 100],
                        [
                            "style" => "max-width:150px;",
                            "class" => "form-control",
                            "value" => $pageNumber,
                            "onchange" => "SoDongHienThi(this.value)",
                        ]
                    )->render();
                    ?>
                </div>
                <?php
                $linkPhanTrang = "/options/index/" . $_Params[0] . "/?keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/options/index/<?php echo $_Params[0]; ?>/?keyword=&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>