<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Dashboard</a></li>
    <!-- <li><a href="/index.php?controller=thongke">Thống kê</a></li> -->
    <li class="text-capitalize"> Danh sách bệnh nhân trong ngày </li>
</ol>
<?php

use Model\Common;
use Module\benhnhan\Model\BenhNhan;
use Model\Locations;
use Model\ThongKe;

?>
<div class="container-fluid">
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <form method="get" action="/thongke/benhnhantrongngay/">
                    <div class="form-group d-flex" style="margin-bottom: 0px;">
                        <input name="indate" value="<?php echo date("Y-m-d", time()); ?>" type="hidden">
                        <div class="col-sm-3 form-group">
                            <?php
                            \Model\FormSearch::NameBenhNhan($_GET['nameBN'] ?? null)->renderHtml2(null, null, 'glyphicon glyphicon-user form-control-feedback');
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <?php
                            \Model\FormSearch::AddressBenhNhan($_REQUEST['address'] ?? null)->renderHtml2(null, null, 'glyphicon glyphicon-home form-control-feedback');
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <?php
                            \Model\FormSearch::PhoneBenhNhan($_GET['phone'] ?? "")->renderHtml2(null, null, 'glyphicon glyphicon-phone form-control-feedback');
                            ?>
                        </div>
                        <div class="col-sm-3 form-group" style="margin-bottom: 0px;">
                            <div class="form-group has-success has-feedback">
                                <label for="inputSuccess2" class="text-capitalize"><em>Nhấn vào đây&nbsp; </em><i class="fa fa-check"></i></label>
                                <button type="submit" style="border-radius: 5px;" class="form-control btn btn-success" name="btnTim">
                                    <i class="fa fa-search-plus"></i>&nbsp;&nbsp; Tìm kiếm
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="box-header">
                <h3 style="margin: 0px;" class="text-center text-uppercase">Danh sách bệnh nhân trong ngày</h3>
                <div class="box-title">
                    <?php
                    Module\benhnhan\Model\btnHtml::btnViewKhachHang();
                    ?>
                    <?php
                    if (\Model\Permission::CheckPremision([
                        \Model\User::QuanLy, \Model\User::Admin
                    ], []) == true) {
                    ?>
                        <a class="btn btn-warning" <?php echo \Model\FormRender::ToolTip("Xuất Excel danh sách bệnh nhân trong ngày"); ?> href="/thongke/exportbenhnhantrongngay/">
                            <i class="fa fa-filter"></i>&nbsp;Export danh sách</a>
                    <?php
                    }
                    ?>
                </div>
            </div>
            <div class="box-body">
                <fieldset>
                    <legend>Danh sách bệnh nhân trong ngày</legend>
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th class="text-center">STT</th>
                                        <th>Mã Khách Hàng</th>
                                        <th>Tên Khách Hàng</th>
                                        <th>Giới Tính</th>
                                        <th>Ngày Sinh</th>
                                        <th>CMND</th>
                                        <th>Địa Chỉ</th>
                                        <!-- <th>Tỉnh/Thành Phố</th> -->
                                        <!-- <th>Quận/Huyện</th> -->
                                        <!-- <th>Phường/Xã</th> -->
                                        <th>Điện Thoại</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $danhsach = $data['items'];
                                    // var_dump($danhsach);
                                    foreach ($danhsach as $index => $item) {
                                        $_item = new BenhNhan($item);
                                    ?>
                                        <tr>
                                            <!-- <td>
                                                <?php
                                                echo Module\benhnhan\Model\btnHtml::btnSuaKhachHang($_item->Id);
                                                echo Module\benhnhan\Model\btnHtml::btnXoaKhachHang($_item->Id);
                                                echo Module\benhnhan\Model\btnHtml::btnchitiet($_item->Id);
                                                ?>
                                            </td> -->
                                            <td class="text-center"><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></td>
                                            <td><?php echo $_item->Id; ?></td>
                                            <td><?php echo $_item->Name; ?></td>
                                            <td><?php echo $_item->Gioitinh(); ?></td>
                                            <td><?php echo Common::ForMatDMY($_item->Ngaysinh); ?></td>
                                            <td><?php echo $_item->CMND; ?></td>
                                            <td><?php echo $_item->Address; ?></td>
                                            <td><?php echo $_item->Phone; ?></td>
                                        </tr>
                                    <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </fieldset>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?controller=thongke&action=benhnhantrongngay&keyword={$params["nameBN"]}&keyword={$params["address"]}&keyword={$params["phone"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?controller=thongke&action=benhnhantrongngay&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>