<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Dashboard</a></li>
    <!-- <li><a href="/index.php?controller=thongke">Thống kê</a></li> -->
    <li class="text-capitalize"> Danh sách thuốc cận date ( Sắp hết hạn ) </li>
</ol>
<?php

use Model\Common;
use Module\benhnhan\Model\BenhNhan;
use Model\Locations;
use Model\ThongKe;
?>
<div class="container-fluid">
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <form method="get" action="/thongke/thuocsaphethan/">
                    <div class="form-group d-flex" style="margin-bottom: 0px;">
                        <div class="col-sm-10 form-group" style="margin-bottom: 0px;">
                            <?php
                            \Model\FormSearch::KeyWordDashboard("Mã phiếu hoặc mã thuốc", $_REQUEST['keyword'] ?? null, "Nhập vào mã phiếu hoặc mã thuốc để tìm kiếm...")->renderHtml2(null, null, 'glyphicon glyphicon-barcode form-control-feedback');
                            ?>
                        </div>
                        <div class="col-sm-2 form-group" style="margin-bottom: 0px;">
                            <div class="form-group has-success has-feedback">
                                <label for="inputSuccess2" class="text-capitalize"><em>Nhấn vào đây&nbsp; </em><i class="fa fa-check"></i></label>
                                <button type="submit" style="border-radius: 5px;" class="form-control btn btn-success" name="btnTim">
                                    <i class="fa fa-search-plus"></i>&nbsp;&nbsp; Tìm kiếm
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="box-header">
                <h3 style="margin: 0px;" class="text-center text-uppercase">Danh sách thuốc cận date ( Sắp hết hạn )</h3>
                <div class="box-title">
                    <?php
                    if (\Model\Permission::CheckPremision([
                        \Model\User::QuanLy, \Model\User::Admin
                    ], []) == true) {
                    ?>
                        <a class="btn btn-warning" <?php echo \Model\FormRender::ToolTip("Xuất Excel danh sách thuốc có hạn sử dụng sắp hết"); ?> href="/thongke/exportthuocsaphet/">
                            <i class="fa fa-filter"></i>&nbsp;Export danh sách
                        </a>
                    <?php
                    }
                    ?>
                </div>
            </div>
            <div class="box-body">
                <fieldset>
                    <legend>Danh sách thuốc sắp hết hạn</legend>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">STT</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Thuộc mã phiếu</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Tên thuốc</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Số lô</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nước sản xuất</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Hạn sử dụng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php

                                    use Model\Notions;
                                    use Module\quanlythuoc\Model\SanPham;

                                    $index = 0;
                                    $danhsach = $data['items'];
                                    // var_dump($danhsach);
                                    foreach ($danhsach as $value) {
                                        $thuoc = new SanPham($value["IdThuoc"]);
                                    ?>
                                        <tr role="row" class="even">
                                            <td class="sorting_1 text-center"><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></td>
                                            <td><?php echo $value['IdPhieu'] ?></td>
                                            <td><?php echo $thuoc->Name . ' (' . $value['IdThuoc'] . ')'; ?></td>
                                            <td><?php echo $value['SoLo'] ?></td>
                                            <td><?php echo $value['NuocSanXuat'] ?></td>
                                            <td><?php echo Common::ForMatDMY($value['HanSuDung']) ?></td>
                                        </tr>
                                    <?php
                                        $index++;
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </fieldset>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?controller=thongke&action=thuocsaphethan&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?controller=thongke&action=thuocsaphethan&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>