<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=quanlythuoc&controller=phieuxuatnhap&action=index"> Danh Sách Phiếu</a></li>
    <li> Thông Tin Chi Tiết Của Phiếu </li>
</ol>
<?php

use Model\Common;
use Model\FormRender;
use Model\OptionsService;
use Module\quanlythuoc\Model\PhieuXuatNhap;
use Module\quanlythuoc\Model\PhieuXuatNhapChiTiet;

$roleDetail = new Model\Role();
$itemSP = new PhieuXuatNhap($data);

?>
<div class="container">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thông Tin Chi Tiết Của Phiếu <?php echo $itemSP->IdPhieu;?> </h3>
        </div>
        <div class="box-body">
            <div class="col-md-12">
                <fieldset>
                    <legend>Thông tin phiếu</legend>
                    <table class="table table-bordered">
                        <tr>
                            <th>Mã Phiếu</th>
                            <td><?php echo $itemSP->IdPhieu ?></td>
                            <th>Loại phiếu</th>
                            <td><?php echo $itemSP->XuatNhap(); ?></td>
                            <th>Tổng tiền</th>
                            <td><?php echo $itemSP->getTongTien(); ?></td>
                        </tr>
                        <tr>
                            <td colspan="6"><strong>Nội Dung: </strong> <?php echo $itemSP->NoiDungPhieu ?></td>
                        </tr>
                        <tr>
                            <td colspan="6"><strong>Ghi chú: </strong> <?php echo $itemSP->GhiChu ?></td>
                        </tr>
                    </table>
                </fieldset>

            </div>
            <div class="col-md-12">
                <fieldset>
                    <legend>Danh sách thuốc</legend>
                    <table class="table table-bordered" style="margin-bottom: 5px;" >
                        <tr>
                            <th>Mã thuốc </th>
                            <th>Thuốc <?php FormRender::ToolTipElement("Tên thuốc"); ?></th>
                            <th>Số lượng <?php FormRender::ToolTipElement("Số lượng nhập xuất phiếu"); ?></th>
                            <th>Số Lô <?php FormRender::ToolTipElement("Số lô sản phẩm"); ?></th>
                            <th>Hạn sử dụng <?php FormRender::ToolTipElement("Hạn sử dụng"); ?></th>
                            <th>Giá <?php FormRender::ToolTipElement("Giá nhập xuất phiếu"); ?></th>
                            <th>Thành tiền <?php FormRender::ToolTipElement("Thành tiền"); ?></th>
                        </tr>
                        <?php
                        foreach ($itemSP->PhieuChiTiet() as $key => $value) {
                            $_chiTiet = new PhieuXuatNhapChiTiet($value);
                        ?>
                            <tr>
                                <td><?php echo $_chiTiet->SanPham()->Id ?></td>
                                <td><?php echo $_chiTiet->SanPham()->Name ?></td>
                                <td><b><?php echo $_chiTiet->SoLuong ?></b></td>
                                <td><?php echo $_chiTiet->SoLo ?></td>
                                <td><?php echo $_chiTiet->HanSuDung() ?></td>
                                <td><b><?php echo $_chiTiet->Price() ?></b></td>
                                <td><b><?php echo $_chiTiet->ThanhTien(); ?></b></td>
                            </tr>
                        <?php
                        }
                        ?>
                        <tr>
                            <td colspan="6" class="text-right"> <b>Tổng Tiền</b></td>
                            <td><b><?php echo $itemSP->getTongTien(); ?></b></td>
                        </tr>
                    </table>
                </fieldset>
            </div>
        </div>
    </div>
</div>